/* Generated by Yosys 0.32+51 (git sha1 6405bbab1, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module fa(a, b, cin, s, co);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  input a;
  wire a;
  input b;
  wire b;
  wire c0;
  wire c1;
  input cin;
  wire cin;
  output co;
  wire co;
  wire \m0.a ;
  wire \m0.b ;
  wire \m0.co ;
  wire \m0.s ;
  wire \m1.a ;
  wire \m1.b ;
  wire \m1.co ;
  wire \m1.s ;
  output s;
  wire s;
  wire s0;
  sky130_fd_sc_hd__xor3_1 _5_ (
    .A(_1_),
    .B(_0_),
    .C(_2_),
    .X(_4_)
  );
  sky130_fd_sc_hd__maj3_1 _6_ (
    .A(_1_),
    .B(_0_),
    .C(_2_),
    .X(_3_)
  );
  assign \m1.a  = cin;
  assign \m1.b  = s0;
  assign c1 = \m1.co ;
  assign s = \m1.s ;
  assign \m0.a  = a;
  assign \m0.b  = b;
  assign c0 = \m0.co ;
  assign s0 = \m0.s ;
  assign _1_ = b;
  assign _0_ = a;
  assign _2_ = cin;
  assign \m1.s  = _4_;
  assign co = _3_;
endmodule
