/* Generated by Yosys 0.32+51 (git sha1 6405bbab1, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module dff_syncres(clk, sync_reset, d, q);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  wire q;
  input sync_reset;
  wire sync_reset;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _4_ (
    .A(_1_),
    .SLEEP(_2_),
    .X(_0_)
  );
  sky130_fd_sc_hd__dfxtp_1 _5_ (
    .CLK(clk),
    .D(_3_),
    .Q(q)
  );
  assign _1_ = d;
  assign _2_ = sync_reset;
  assign _3_ = _0_;
endmodule
