/* Generated by Yosys 0.32+51 (git sha1 6405bbab1, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module mul9(a, y);
  input [2:0] a;
  wire [2:0] a;
  output [5:0] y;
  wire [5:0] y;
  assign y = { a, a };
endmodule
