/* Generated by Yosys 0.32+51 (git sha1 6405bbab1, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module ripple_carry(x, y, sum);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  wire [8:0] co;
  wire \genblk1[0].genblk1.m0.a ;
  wire \genblk1[0].genblk1.m0.b ;
  wire \genblk1[0].genblk1.m0.cin ;
  wire \genblk1[0].genblk1.m0.cout ;
  wire \genblk1[0].genblk1.m0.s ;
  wire \genblk1[1].genblk1.mx.a ;
  wire \genblk1[1].genblk1.mx.b ;
  wire \genblk1[1].genblk1.mx.cin ;
  wire \genblk1[1].genblk1.mx.cout ;
  wire \genblk1[1].genblk1.mx.s ;
  wire \genblk1[2].genblk1.mx.a ;
  wire \genblk1[2].genblk1.mx.b ;
  wire \genblk1[2].genblk1.mx.cin ;
  wire \genblk1[2].genblk1.mx.cout ;
  wire \genblk1[2].genblk1.mx.s ;
  wire \genblk1[3].genblk1.mx.a ;
  wire \genblk1[3].genblk1.mx.b ;
  wire \genblk1[3].genblk1.mx.cin ;
  wire \genblk1[3].genblk1.mx.cout ;
  wire \genblk1[3].genblk1.mx.s ;
  wire \genblk1[4].genblk1.mx.a ;
  wire \genblk1[4].genblk1.mx.b ;
  wire \genblk1[4].genblk1.mx.cin ;
  wire \genblk1[4].genblk1.mx.cout ;
  wire \genblk1[4].genblk1.mx.s ;
  wire \genblk1[5].genblk1.mx.a ;
  wire \genblk1[5].genblk1.mx.b ;
  wire \genblk1[5].genblk1.mx.cin ;
  wire \genblk1[5].genblk1.mx.cout ;
  wire \genblk1[5].genblk1.mx.s ;
  wire \genblk1[6].genblk1.mx.a ;
  wire \genblk1[6].genblk1.mx.b ;
  wire \genblk1[6].genblk1.mx.cin ;
  wire \genblk1[6].genblk1.mx.cout ;
  wire \genblk1[6].genblk1.mx.s ;
  wire \genblk1[7].genblk1.mx.a ;
  wire \genblk1[7].genblk1.mx.b ;
  wire \genblk1[7].genblk1.mx.cin ;
  wire \genblk1[7].genblk1.mx.cout ;
  wire \genblk1[7].genblk1.mx.s ;
  output [8:0] sum;
  wire [8:0] sum;
  input [7:0] x;
  wire [7:0] x;
  input [7:0] y;
  wire [7:0] y;
  sky130_fd_sc_hd__maj3_1 _64_ (
    .A(_05_),
    .B(_03_),
    .C(_04_),
    .X(_06_)
  );
  sky130_fd_sc_hd__xor3_1 _65_ (
    .A(_05_),
    .B(_03_),
    .C(_04_),
    .X(_07_)
  );
  sky130_fd_sc_hd__maj3_1 _66_ (
    .A(_13_),
    .B(_11_),
    .C(_12_),
    .X(_14_)
  );
  sky130_fd_sc_hd__xor3_1 _67_ (
    .A(_13_),
    .B(_11_),
    .C(_12_),
    .X(_15_)
  );
  sky130_fd_sc_hd__maj3_1 _68_ (
    .A(_21_),
    .B(_19_),
    .C(_20_),
    .X(_22_)
  );
  sky130_fd_sc_hd__xor3_1 _69_ (
    .A(_21_),
    .B(_19_),
    .C(_20_),
    .X(_23_)
  );
  sky130_fd_sc_hd__maj3_1 _70_ (
    .A(_29_),
    .B(_27_),
    .C(_28_),
    .X(_30_)
  );
  sky130_fd_sc_hd__xor3_1 _71_ (
    .A(_29_),
    .B(_27_),
    .C(_28_),
    .X(_31_)
  );
  sky130_fd_sc_hd__maj3_1 _72_ (
    .A(_37_),
    .B(_35_),
    .C(_36_),
    .X(_38_)
  );
  sky130_fd_sc_hd__xor3_1 _73_ (
    .A(_37_),
    .B(_35_),
    .C(_36_),
    .X(_39_)
  );
  sky130_fd_sc_hd__maj3_1 _74_ (
    .A(_45_),
    .B(_43_),
    .C(_44_),
    .X(_46_)
  );
  sky130_fd_sc_hd__xor3_1 _75_ (
    .A(_45_),
    .B(_43_),
    .C(_44_),
    .X(_47_)
  );
  sky130_fd_sc_hd__maj3_1 _76_ (
    .A(_53_),
    .B(_51_),
    .C(_52_),
    .X(_54_)
  );
  sky130_fd_sc_hd__xor3_1 _77_ (
    .A(_53_),
    .B(_51_),
    .C(_52_),
    .X(_55_)
  );
  sky130_fd_sc_hd__maj3_1 _78_ (
    .A(_61_),
    .B(_59_),
    .C(_60_),
    .X(_62_)
  );
  sky130_fd_sc_hd__xor3_1 _79_ (
    .A(_61_),
    .B(_59_),
    .C(_60_),
    .X(_63_)
  );
  assign co[0] = 1'hx;
  assign sum[8] = co[8];
  assign _61_ = \genblk1[7].genblk1.mx.cin ;
  assign _59_ = \genblk1[7].genblk1.mx.a ;
  assign _60_ = \genblk1[7].genblk1.mx.b ;
  assign \genblk1[7].genblk1.mx.cout  = _62_;
  assign \genblk1[7].genblk1.mx.s  = _63_;
  assign \genblk1[7].genblk1.mx.a  = x[7];
  assign \genblk1[7].genblk1.mx.b  = y[7];
  assign \genblk1[7].genblk1.mx.cin  = co[7];
  assign co[8] = \genblk1[7].genblk1.mx.cout ;
  assign sum[7] = \genblk1[7].genblk1.mx.s ;
  assign _53_ = \genblk1[6].genblk1.mx.cin ;
  assign _51_ = \genblk1[6].genblk1.mx.a ;
  assign _52_ = \genblk1[6].genblk1.mx.b ;
  assign \genblk1[6].genblk1.mx.cout  = _54_;
  assign \genblk1[6].genblk1.mx.s  = _55_;
  assign \genblk1[6].genblk1.mx.a  = x[6];
  assign \genblk1[6].genblk1.mx.b  = y[6];
  assign \genblk1[6].genblk1.mx.cin  = co[6];
  assign co[7] = \genblk1[6].genblk1.mx.cout ;
  assign sum[6] = \genblk1[6].genblk1.mx.s ;
  assign _45_ = \genblk1[5].genblk1.mx.cin ;
  assign _43_ = \genblk1[5].genblk1.mx.a ;
  assign _44_ = \genblk1[5].genblk1.mx.b ;
  assign \genblk1[5].genblk1.mx.cout  = _46_;
  assign \genblk1[5].genblk1.mx.s  = _47_;
  assign \genblk1[5].genblk1.mx.a  = x[5];
  assign \genblk1[5].genblk1.mx.b  = y[5];
  assign \genblk1[5].genblk1.mx.cin  = co[5];
  assign co[6] = \genblk1[5].genblk1.mx.cout ;
  assign sum[5] = \genblk1[5].genblk1.mx.s ;
  assign _37_ = \genblk1[4].genblk1.mx.cin ;
  assign _35_ = \genblk1[4].genblk1.mx.a ;
  assign _36_ = \genblk1[4].genblk1.mx.b ;
  assign \genblk1[4].genblk1.mx.cout  = _38_;
  assign \genblk1[4].genblk1.mx.s  = _39_;
  assign \genblk1[4].genblk1.mx.a  = x[4];
  assign \genblk1[4].genblk1.mx.b  = y[4];
  assign \genblk1[4].genblk1.mx.cin  = co[4];
  assign co[5] = \genblk1[4].genblk1.mx.cout ;
  assign sum[4] = \genblk1[4].genblk1.mx.s ;
  assign _29_ = \genblk1[3].genblk1.mx.cin ;
  assign _27_ = \genblk1[3].genblk1.mx.a ;
  assign _28_ = \genblk1[3].genblk1.mx.b ;
  assign \genblk1[3].genblk1.mx.cout  = _30_;
  assign \genblk1[3].genblk1.mx.s  = _31_;
  assign \genblk1[3].genblk1.mx.a  = x[3];
  assign \genblk1[3].genblk1.mx.b  = y[3];
  assign \genblk1[3].genblk1.mx.cin  = co[3];
  assign co[4] = \genblk1[3].genblk1.mx.cout ;
  assign sum[3] = \genblk1[3].genblk1.mx.s ;
  assign _21_ = \genblk1[2].genblk1.mx.cin ;
  assign _19_ = \genblk1[2].genblk1.mx.a ;
  assign _20_ = \genblk1[2].genblk1.mx.b ;
  assign \genblk1[2].genblk1.mx.cout  = _22_;
  assign \genblk1[2].genblk1.mx.s  = _23_;
  assign \genblk1[2].genblk1.mx.a  = x[2];
  assign \genblk1[2].genblk1.mx.b  = y[2];
  assign \genblk1[2].genblk1.mx.cin  = co[2];
  assign co[3] = \genblk1[2].genblk1.mx.cout ;
  assign sum[2] = \genblk1[2].genblk1.mx.s ;
  assign _13_ = \genblk1[1].genblk1.mx.cin ;
  assign _11_ = \genblk1[1].genblk1.mx.a ;
  assign _12_ = \genblk1[1].genblk1.mx.b ;
  assign \genblk1[1].genblk1.mx.cout  = _14_;
  assign \genblk1[1].genblk1.mx.s  = _15_;
  assign \genblk1[1].genblk1.mx.a  = x[1];
  assign \genblk1[1].genblk1.mx.b  = y[1];
  assign \genblk1[1].genblk1.mx.cin  = co[1];
  assign co[2] = \genblk1[1].genblk1.mx.cout ;
  assign sum[1] = \genblk1[1].genblk1.mx.s ;
  assign _05_ = \genblk1[0].genblk1.m0.cin ;
  assign _03_ = \genblk1[0].genblk1.m0.a ;
  assign _04_ = \genblk1[0].genblk1.m0.b ;
  assign \genblk1[0].genblk1.m0.cout  = _06_;
  assign \genblk1[0].genblk1.m0.s  = _07_;
  assign \genblk1[0].genblk1.m0.a  = x[0];
  assign \genblk1[0].genblk1.m0.b  = y[0];
  assign \genblk1[0].genblk1.m0.cin  = 1'h0;
  assign co[1] = \genblk1[0].genblk1.m0.cout ;
  assign sum[0] = \genblk1[0].genblk1.m0.s ;
endmodule
